govitradata:
    container_name: govitra-data
    image: bqqbarbhg/govitra-data
    env_file:
        - common.env

govitravideos:
    container_name: govitra-videos
    image: bqqbarbhg/govitra-nginx
    env_file:
        - common.env
    volumes_from:
        - govitradata

govitraapi:
    container_name: govitra-api
    image: bqqbarbhg/govitra-uploader
    env_file:
        - common.env
        - govitra.env
    volumes_from:
        - govitradata

