govitradata:
    container_name: govitra-data
    image: bqqbarbhg/govitra-data-arm

govitravideos:
    container_name: govitra-videos
    image: bqqbarbhg/govitra-nginx-arm
    hostname: govitra-videos
    volumes_from:
        - govitradata
    links:
        - govitraapi

govitraapi:
    container_name: govitra-api
    image: bqqbarbhg/govitra-uploader-arm
    hostname: govitra-api
    env_file:
        - govitra.env
    volumes_from:
        - govitradata

